# Merging data from OWID and WorldBank

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import altair as alt
import math
import os

In [2]:
os.listdir('output')

['owid_china_impute.csv',
 'owid_india_impute.csv',
 'owid_us_impute.csv',
 'worldbank_china_impute.csv',
 'worldbank_india_impute.csv',
 'worldbank_us_impute.csv']

In [3]:
# function to read specific csv files from the output folder and merge them
def merge_owid_worldbank_data(country):
    
    country = country.lower() # just in case, lol
    
    df_owid = pd.read_csv(f'output/owid_{country}_impute.csv')
    df_worldbank = pd.read_csv(f'output/worldbank_{country}_impute.csv')
    
    df_country = df_owid.merge(df_worldbank, how='left', on='year')
    df_country.drop(['iso_code_x', 'country_x'], axis=1, inplace=True)
    df_country.rename(columns={'iso_code_y': 'iso_code',
                               'country_y': 'country'}, inplace=True)
    
    # save merged dfs
    df_country.to_csv(f'output/merged_{country}.csv', index=False)
    
    return df_country

In [4]:
df_china = merge_owid_worldbank_data('china')
df_china

,year,co2,co2_growth_prct,co2_growth_abs,co2_per_capita,share_global_co2,cumulative_co2,share_global_cumulative_co2,co2_per_gdp,coal_co2,...,Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Total greenhouse gas emissions (% change from 1990),Total greenhouse gas emissions (kt of CO2 equivalent),Urban population,Urban population (% of total population),Urban population growth (annual %),iso_code,country
0,2001,3514.934,2.20,75.782,2.706,13.81,78398.967,7.32,0.555000,2428.857,...,18.958519,28.334999,0.964620,32.184715,4.791440e+06,471767321.0,37.093,4.059566,CHN,China
1,2002,3872.595,10.18,357.662,2.962,14.87,82271.562,7.50,0.568000,2778.770,...,17.618628,26.978399,0.943115,40.646591,5.100860e+06,491993700.0,38.425,4.198001,CHN,China
2,2003,4545.014,17.36,672.419,3.456,16.61,86816.576,7.72,0.627000,3319.280,...,15.037040,23.841499,1.001983,59.966148,5.717660e+06,512473984.0,39.776,4.078404,CHN,China
3,2004,5223.755,14.93,678.741,3.948,18.25,92040.331,7.99,0.667000,3835.288,...,16.223266,20.160801,1.022370,82.821379,6.467060e+06,533257098.0,41.144,3.975372,CHN,China
4,2005,5876.555,12.50,652.801,4.416,19.85,97916.886,8.28,0.683000,4424.390,...,16.175025,17.440800,1.053162,100.467167,7.194480e+06,554367818.0,42.522,3.882473,CHN,China
5,2006,6488.804,10.42,612.248,4.848,21.22,104405.690,8.61,0.684000,4905.374,...,15.592783,16.385099,0.988040,120.244306,7.879330e+06,575118254.0,43.868,3.674728,CHN,China
6,2007,6978.612,7.55,489.808,5.185,22.16,111384.302,8.95,0.674000,5289.904,...,15.263347,14.883700,0.991550,134.390133,8.497040e+06,595670841.0,45.199,3.511256,CHN,China
7,2008,7496.832,7.43,518.220,5.539,23.38,118881.134,9.31,0.694000,5729.474,...,17.737444,14.137800,0.996970,157.458544,8.786120e+06,616481190.0,46.539,3.433958,CHN,China
8,2009,7886.533,5.20,389.701,5.794,24.95,126767.667,9.69,0.682000,6028.500,...,17.863798,13.431900,1.003350,172.749831,9.377660e+06,637407288.0,47.880,3.338102,CHN,China
9,2010,8616.653,9.26,730.120,6.295,25.84,135384.319,10.09,0.670000,6568.794,...,18.622826,12.261300,0.988950,187.303978,1.020382e+07,658498663.0,49.226,3.255365,CHN,China
10,2011,9528.556,10.58,911.903,6.922,27.64,144912.875,10.53,0.697000,7309.786,...,16.761770,11.338200,0.992420,209.922085,1.107455e+07,678933504.0,50.511,3.056070,CHN,China
11,2012,9775.622,2.59,247.066,7.062,27.95,154688.497,10.97,0.681000,7464.806,...,19.966249,11.536700,0.997180,219.952477,1.139983e+07,699187267.0,51.765,2.939542,CHN,China
12,2013,9952.744,1.81,177.122,7.151,28.21,164641.241,11.39,0.650000,7493.454,...,20.296227,11.522000,1.006090,99.634651,1.185453e+07,719587859.0,53.013,2.876002,CHN,China
13,2014,9985.583,0.33,32.840,7.135,28.10,174626.824,11.79,0.616000,7425.069,...,22.609154,12.061400,1.009480,101.464867,1.186531e+07,740239259.0,54.259,2.829483,CHN,China
14,2015,9848.420,-1.37,-137.164,7.000,27.74,184475.244,12.16,0.589000,7266.979,...,23.926817,12.245300,1.011580,96.369996,1.185929e+07,761027100.0,55.500,2.769551,CHN,China
15,2016,9720.444,-1.30,-127.976,6.874,27.42,194195.688,12.51,0.563000,7071.406,...,-1.722419,12.589700,1.010140,48.636464,1.185718e+07,782199374.0,56.736,2.744069,CHN,China
16,2017,9920.459,2.06,200.015,6.981,27.61,204116.147,12.85,0.564000,7137.264,...,5.647923,12.863600,1.013220,52.068858,1.205805e+07,803554542.0,57.960,2.693540,CHN,China
17,2018,10289.990,3.72,369.530,7.208,28.08,214406.137,13.19,0.567000,7316.400,...,5.140052,13.123800,1.014310,50.187239,1.235524e+07,823827650.0,59.152,2.491628,CHN,China
18,2019,10489.989,1.94,199.999,7.316,28.58,224896.125,13.53,34.581311,7377.670,...,2.437522,31.107903,1.015290,-108.859164,3.959269e+06,842933962.0,60.308,2.292727,CHN,China
19,2020,10667.887,1.70,177.899,7.412,30.65,235564.013,13.89,38.993568,7421.101,...,1.727749,31.134701,1.012870,-117.273055,3.990007e+06,861289359.0,61.428,2.154190,CHN,China

In [5]:
df_us = merge_owid_worldbank_data('us')
df_us

,year,co2,co2_growth_prct,co2_growth_abs,co2_per_capita,share_global_co2,cumulative_co2,share_global_cumulative_co2,co2_per_gdp,coal_co2,...,Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Total greenhouse gas emissions (% change from 1990),Total greenhouse gas emissions (kt of CO2 equivalent),Urban population,Urban population (% of total population),Urban population growth (annual %),iso_code,country
0,2001,5904.882,-1.76,-105.627,20.747,23.20,310217.648,28.98,0.451000,2115.059,...,6.783992,4.678700,0.782444,11.165770,6.806970e+06,225792302.0,79.234,1.213380,USA,United States
1,2002,5946.771,0.71,41.889,20.700,22.84,316164.418,28.83,0.446000,2119.322,...,8.646361,4.840800,0.748230,13.782275,6.646960e+06,228400290.0,79.409,1.148419,USA,United States
2,2003,6011.837,1.09,65.067,20.744,21.97,322176.256,28.67,0.438000,2158.577,...,8.889376,5.326300,0.886371,13.936582,6.706390e+06,230876596.0,79.583,1.078360,USA,United States
3,2004,6114.007,1.70,102.169,20.913,21.36,328290.263,28.48,0.430000,2190.331,...,8.630186,5.477700,1.014797,18.059992,6.787570e+06,233532722.0,79.757,1.143885,USA,United States
4,2005,6134.521,0.34,20.515,20.795,20.72,334424.784,28.29,0.417000,2214.838,...,8.578466,5.841200,1.003870,17.058327,6.801820e+06,236200507.0,79.928,1.135885,USA,United States
5,2006,6051.668,-1.35,-82.853,20.324,19.79,340476.452,28.08,0.401000,2183.112,...,9.244631,6.396700,1.378431,13.982730,6.707430e+06,238999326.0,80.099,1.177968,USA,United States
6,2007,6131.004,1.31,79.336,20.395,19.47,346607.456,27.86,0.399000,2208.712,...,8.367764,6.304200,1.634938,16.180624,6.797860e+06,241795278.0,80.269,1.163068,USA,United States
7,2008,5914.078,-3.54,-216.926,19.487,18.44,352521.534,27.62,0.386000,2174.329,...,9.003541,6.845600,1.922989,8.358701,6.619980e+06,244607104.0,80.438,1.156186,USA,United States
8,2009,5478.210,-7.37,-435.868,17.885,17.33,357999.744,27.37,0.368000,1905.943,...,10.291845,7.354400,2.321405,7.626602,6.194450e+06,247276259.0,80.606,1.085290,USA,United States
9,2010,5675.786,3.61,197.577,18.368,17.02,363675.530,27.12,0.372000,2013.304,...,10.120355,7.435700,2.477131,9.407540,6.442580e+06,249849720.0,80.772,1.035345,USA,United States
10,2011,5540.173,-2.39,-135.613,17.781,16.07,369215.704,26.84,0.357000,1903.555,...,12.225714,8.364200,2.431956,7.098335,6.214430e+06,252208133.0,80.944,0.939505,USA,United States
11,2012,5338.698,-3.64,-201.475,17.000,15.26,374554.402,26.55,0.337000,1684.037,...,12.007397,8.728100,2.644710,3.385656,5.968740e+06,254614421.0,81.119,0.949566,USA,United States
12,2013,5474.257,2.54,135.558,17.302,15.52,380028.659,26.28,0.340000,1740.833,...,12.637919,9.083300,0.997100,-23.163034,6.108670e+06,256953576.0,81.299,0.914510,USA,United States
13,2014,5522.807,0.89,48.550,17.331,15.54,385551.466,26.02,0.335000,1734.526,...,12.953827,9.220500,1.004230,-24.419189,6.129040e+06,259430732.0,81.483,0.959431,USA,United States
14,2015,5371.771,-2.73,-151.037,16.741,15.13,390923.236,25.77,0.318000,1504.946,...,13.228593,9.033900,1.005080,-24.417152,6.003650e+06,261950744.0,81.671,0.966675,USA,United States
15,2016,5248.024,-2.30,-123.747,16.247,14.80,396171.260,25.52,0.306000,1379.744,...,7.080988,9.456300,0.996260,-11.165428,5.907270e+06,264473000.0,81.862,0.958268,USA,United States
16,2017,5207.751,-0.77,-40.273,16.020,14.50,401379.012,25.27,0.296000,1338.667,...,29.584271,9.919100,0.993630,-27.628718,5.842800e+06,266788716.0,82.058,0.871785,USA,United States
17,2018,5375.491,3.22,167.739,16.434,14.67,406754.502,25.03,0.296000,1283.532,...,23.259311,10.107200,0.994700,-22.194261,6.023620e+06,268844029.0,82.256,0.767437,USA,United States
18,2019,5255.816,-2.23,-119.674,15.972,14.32,412010.318,24.79,1.864004,1098.854,...,39.431233,41.834903,0.994910,-37.845050,5.878789e+06,270737596.0,82.459,0.701868,USA,United States
19,2020,4712.771,-10.33,-543.046,14.238,13.54,416723.089,24.56,1.873357,888.649,...,41.322246,43.268671,2.476553,-37.970936,5.882386e+06,272364755.0,82.664,0.599211,USA,United States

In [6]:
df_india = merge_owid_worldbank_data('india')
df_india

,year,co2,co2_growth_prct,co2_growth_abs,co2_per_capita,share_global_co2,cumulative_co2,share_global_cumulative_co2,co2_per_gdp,coal_co2,...,Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Total greenhouse gas emissions (% change from 1990),Total greenhouse gas emissions (kt of CO2 equivalent),Urban population,Urban population (% of total population),Urban population growth (annual %),iso_code,country
0,2001,992.560,1.39,13.641,0.923,3.90,19932.284,1.86,0.342000,582.912,...,13.207044,51.858501,0.809880,35.190929,1.741320e+06,300118526.0,27.918,2.631896,IND,India
1,2002,1023.027,3.07,30.467,0.936,3.93,20955.311,1.91,0.342000,599.450,...,12.055161,50.808102,0.830370,38.196166,1.763940e+06,308796506.0,28.244,2.850502,IND,India
2,2003,1059.616,3.58,36.589,0.953,3.87,22014.927,1.96,0.330000,626.782,...,13.469425,50.829800,0.915700,42.459946,1.808910e+06,317584393.0,28.572,2.806108,IND,India
3,2004,1125.471,6.21,65.855,0.996,3.93,23140.399,2.01,0.326000,670.922,...,14.482501,50.072800,0.852040,50.668683,1.894780e+06,326495070.0,28.903,2.767126,IND,India
4,2005,1185.953,5.37,60.482,1.033,4.01,24326.352,2.06,0.320000,722.497,...,16.619018,48.532398,0.895660,52.623872,1.969680e+06,335503761.0,29.235,2.721832,IND,India
5,2006,1259.744,6.22,73.791,1.081,4.12,25586.096,2.11,0.313000,774.666,...,17.540425,46.063202,0.973918,60.934515,2.065570e+06,344622641.0,29.569,2.681686,IND,India
6,2007,1358.152,7.81,98.408,1.148,4.31,26944.249,2.17,0.312000,843.677,...,17.864086,44.903400,0.942560,71.692385,2.209240e+06,353850624.0,29.906,2.642483,IND,India
7,2008,1462.815,7.71,104.662,1.218,4.56,28407.063,2.23,0.318000,912.093,...,16.509834,43.405102,0.967050,75.779430,2.309340e+06,363154576.0,30.246,2.595371,IND,India
8,2009,1612.817,10.25,150.002,1.324,5.10,30019.880,2.30,0.326000,985.349,...,15.660055,42.107498,0.989970,87.018352,2.452660e+06,372465918.0,30.587,2.531697,IND,India
9,2010,1677.888,4.03,65.071,1.359,5.03,31697.767,2.36,0.316000,1017.376,...,16.043744,41.112801,0.989050,99.763086,2.564130e+06,381763164.0,30.930,2.465489,IND,India
10,2011,1780.130,6.09,102.242,1.424,5.16,33477.897,2.43,0.314000,1091.465,...,17.316963,40.577202,0.998530,103.899617,2.671200e+06,391040056.0,31.276,2.400957,IND,India
11,2012,1963.586,10.31,183.456,1.551,5.61,35441.483,2.51,0.330000,1247.112,...,15.732973,39.346100,1.003400,116.444855,2.814000e+06,400416922.0,31.634,2.369631,IND,India
12,2013,2036.937,3.74,73.351,1.590,5.77,37478.420,2.59,0.322000,1320.664,...,17.349314,38.182899,1.072500,404.857818,2.875980e+06,409907903.0,32.003,2.342620,IND,India
13,2014,2185.856,7.31,148.919,1.687,6.15,39664.276,2.68,0.324000,1447.723,...,16.253840,36.053799,1.069620,449.413196,3.048790e+06,419567353.0,32.384,2.329156,IND,India
14,2015,2268.567,3.78,82.712,1.732,6.39,41932.844,2.76,0.312000,1487.726,...,15.343050,34.395901,1.070180,512.375504,3.063650e+06,429428650.0,32.777,2.323154,IND,India
15,2016,2382.223,5.01,113.656,1.799,6.72,44315.067,2.85,0.307000,1530.271,...,1347.135567,33.562901,1.095190,-271.926129,3.103110e+06,439501314.0,33.182,2.318510,IND,India
16,2017,2433.856,2.17,51.633,1.818,6.77,46748.923,2.94,0.294000,1561.224,...,1494.118714,32.212101,1.084020,-289.554863,3.229920e+06,449795398.0,33.600,2.315210,IND,India
17,2018,2599.806,6.82,165.950,1.922,7.09,49348.729,3.04,0.294000,1677.771,...,1640.697246,31.689199,0.482212,-320.232413,3.374990e+06,460304169.0,34.030,2.309470,IND,India
18,2019,2625.968,1.01,26.162,1.922,7.15,51974.697,3.13,1.533459,1677.934,...,1652.053778,-245.508542,1.020170,-594.478113,9.678740e+05,471031529.0,34.472,2.303752,IND,India
19,2020,2441.792,-7.01,-184.176,1.769,7.02,54416.489,3.21,1.531934,1587.552,...,1806.028533,-276.292989,1.007380,-652.041706,9.320663e+05,481980332.0,34.926,2.297828,IND,India